#!/bin/bash

echo -e "\nonce you are in the virtual environment with (venv) appended to your prompt,"
echo -e "tell flask which app to run by running the following command in bash:"
echo -e '"export FLASK_APP=name_of_the_app"\n'
echo -e "once that is set, start it by running:"
echo -e '"flask run --host=0.0.0.0 --port=<port number>"\n'
echo -e 'you can run it in the background by appending " &"'
echo -e 'and you can terminate the app by pressing "Ctrl-C"\n'
