"""empty message

Revision ID: a1b291ccff17
Revises: 
Create Date: 2019-07-27 23:00:21.606746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b291ccff17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.create_table('global_data',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('precip', sa.Float(), nullable=True),
    sa.Column('seaLevel', sa.Float(), nullable=True),
    sa.Column('storms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('loTemp', sa.Float(), nullable=True),
    sa.Column('hiTemp', sa.Float(), nullable=True),
    sa.Column('avgTemp', sa.Float(), nullable=True),
    sa.Column('gust', sa.Float(), nullable=True),
    sa.Column('precip', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('global_data')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
